name: Build Environment
description: "Build the environment using pyproject.toml and uv"

inputs:
  python-version:
    description: 'The Python we shall use'
    required: false
    default: '3.12'

runs:
  using: "composite"

  steps:
    - name: "Build the virtual environment"
      uses: tschm/cradle/actions/environment@main
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the dependencies
      shell: bash
      run : |
        uv pip install -r requirements.txt
