name: Build and Release

on:
  # Trigger on manual dispatch
  workflow_dispatch

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Generate Tag
        uses: ./.github/actions/tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_package: 'false'
