name: Build and Release

on:
  # Trigger on manual dispatch
  workflow_dispatch:
  # Trigger on push to the main branch
  push:
    branches:
      - main

permissions:
  contents: write


jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Tag
        uses: cvxgrp/.github/actions/tag@v2.2.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_package: 'false'
