name: CI

on:
  push:

jobs:
  test-template-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Launch the cradle
        uses: tschm/cradle/actions/cradle@main
        with:
            python-version: '3.12'

      - name: Build LaTeX document
        uses: tschm/cradle/actions/flow@main
        with:
          workflow: latex.yml

      - name: Build Docker image
        uses: tschm/cradle/actions/flow@main
        with:
          workflow: docker.yml

      - name: Test pre-commit flow
        uses: tschm/cradle/actions/flow@main
        with:
          workflow: pre-commit.yml

      - name: Test Marimo flow
        uses: tschm/cradle/actions/flow@main
        with:
          workflow: marimo.yml

      - name: Test ci flow
        uses: tschm/cradle/actions/flow@main
        with:
          workflow: ci.yml
