name: Test Template Workflows

on:
  push:

jobs:
  test-template-workflows:
    strategy:
      matrix:
        python-version: [ '3.12' ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install act
        run: |
          curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
          # Add the installation directory to PATH
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Launch the cradle
        uses: cvxgrp/cradle/actions/cradle@main
        with:
            python-version: '3.12'

      - name: Run copier
        working-directory: .
        shell: bash
        run: |
          copier copy . template --data-file .github/data.yaml

      - name: Prepare the repo
        working-directory: template
        shell: bash
        run: |
          # otherwise the pre-commit hooks won't "see" files
          # also act needs to have the commit in place
          git init -b main
          git add .
          git commit -m "Initial commit"

      - name: Test Marimo flow
        uses: cvxgrp/cradle/actions/flow@main
        with:
          working-directory: template
          workflow: marimo.yml

      - name: Test pre-commit flow
        uses: cvxgrp/cradle/actions/flow@main
        with:
          working-directory: template
          workflow: pre-commit.yml
