name: Test Template Workflows

on:
  push:

jobs:
  test-template-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install act
        run: |
          curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
          # Add the installation directory to PATH
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Verify act installation
        run: |
          act --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Set Git user name and email for CI/CD
      - name: Set Git user for CI/CD
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "CI User"
