name: LATEX

on:
  push:

jobs:
  test-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Launch the cradle
        uses: tschm/cradle/actions/cradle@v0.1.52
        with:
            python-version: '3.12'

      - name: Build LaTeX document
        uses: tschm/cradle/actions/flow@v0.1.52
        with:
          workflow: latex.yml
