# Workflow to automatically bump the version and create a new tag
# This workflow is manually triggered via the GitHub UI

name: Bump version
on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      tag:
        description: 'Release tag (e.g. v1.2.3)'
        required: true
        type: string

# Permissions needed for the workflow
permissions:
  contents: write  # Allows the workflow to write to the repository (create tags)

jobs:
  # Job to generate a new version tag
  tagging:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.set_tag.outputs.tag }}  # Output the tag to be used by other jobs

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4  # Check out the repository code

      - name: Set Tag from Input
        id: set_tag
        run: |
          echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          echo "Using tag: ${{ github.event.inputs.tag }}"

      - name: Create and Push Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a {${{ github.event.inputs.tag }} -m "Release {% raw %}${{ github.event.inputs.tag }}"
          git push origin ${{ github.event.inputs.tag }}
