name: Bump version
on:
  workflow_dispatch

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Generate Tag
        id: tag
        uses: ./.github/actions/tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  debug:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Print Tag
        run: |
          echo ${{ needs.build.outputs.new_tag }}
