name: Bump version
on:
  workflow_dispatch

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}

    steps:
      - name: Generate Tag
        id: tag
        uses: tschm/cradle/actions/tag@v0.1.64
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


  debug:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Print Tag
        run: |
          echo "A: ${{ needs.build.outputs.new_tag }}"
