name: Bump version
on:
  workflow_dispatch

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ env.new_tag }}

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Generate Tag
        id: tag
        uses: ./.github/actions/tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      #- name: Set Output for Job
      #  id: set_tag
      #  run: echo "new_tag=${{ steps.tag.outputs.new_tag }}" >> "$GITHUB_OUTPUT"

      - name: Print Tag 1
        run: |
          echo "Generated tag 2: ${{ env.new_tag }}"

  debug:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Print Tag 2
        run: |
          echo "A: ${{ needs.build.outputs.new_tag }}"
          echo "B: ${{ env.new_tag }}"
