name: Bump version
on:
  workflow_dispatch

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Generate Tag
        id: tag
        uses: ./.github/actions/tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Tag
        run: |
          echo ${{ tag.outputs.new_tag }}
